import { uniqueId } from 'lodash';
import { useTranslation } from 'react-i18next';

import {
  IconAward,
  IconBoxMultiple,
  IconPoint,
  IconAlertCircle,
  IconNotes,
  IconCalendar,
  IconMail,
  IconTicket,
  IconEdit,
  IconCurrencyDollar,
  IconApps,
  IconFileDescription,
  IconFileDots,
  IconFiles,
  IconFileText,
  IconBan,
  IconStar,
  IconMoodSmile,
  IconBorderAll,
  IconBorderHorizontal,
  IconBorderInner,
  IconBorderVertical,
  IconBorderTop,
  IconUserCircle,
  IconPackage,
  IconMessage2,
  IconBasket,
  IconChartLine,
  IconChartArcs,
  IconChartCandle,
  IconChartArea,
  IconChartDots,
  IconChartDonut3,
  IconChartRadar,
  IconLogin,
  IconUserPlus,
  IconRotate,
  IconBox,
  IconShoppingCart,
  IconAperture,
  IconLayout,
  IconSettings,
  IconHelp,
  IconZoomCode,
  IconBoxAlignBottom,
  IconBoxAlignLeft,
  IconBorderStyle2,
  IconAppWindow,
  IconNotebook,
  IconFileCheck,
  IconChartHistogram,
  IconChartPie2,
  IconChartScatter,
  IconChartPpf,
  IconChartArcs3,
  IconListTree,
  IconRobot,
  IconUsers,
} from '@tabler/icons-react';

// MenuItems ska nu vara en funktion som använder useTranslation
const useMenuItems = () => {
  const { t } = useTranslation();

  return [
  {
    navlabel: true,
    subheader: t('navigation.dashboard'),
  },

  {
    id: uniqueId(),
    title: t('navigation.Modern'),
    icon: IconAperture,
    href: '/dashboards/modern',
    chip: 'New',
    chipColor: 'secondary',
  },
  {
    id: uniqueId(),
    title: t('navigation.eCommerce'),
    icon: IconShoppingCart,
    href: '/dashboards/ecommerce',
  },
  {
    id: uniqueId(),
    title: t('navigation.frontendPages'),
    icon: IconAppWindow,
    href: '/frontend-pages/',
    children: [
      {
        id: uniqueId(),
        title: t('navigation.homepage'),
        icon: IconPoint,
        href: '/frontend-pages/homepage',
      },
      {
        id: uniqueId(),
        title: t('navigation.aboutUs'),
        icon: IconPoint,
        href: '/frontend-pages/about',
      },
      {
        id: uniqueId(),
        title: t('navigation.Blog'),
        icon: IconPoint,
        href: '/frontend-pages/blog',
      },
      {
        id: uniqueId(),
        title: t('navigation.blogDetails'),
        icon: IconPoint,
        href: '/frontend-pages/blog/detail/streaming-video-way-before-it-was-cool-go-dark-tomorrow',
      },
      {
        id: uniqueId(),
        title: t('navigation.contact'),
        icon: IconPoint,
        href: '/frontend-pages/contact',
      },
      {
        id: uniqueId(),
        title: t('navigation.portfolio'),
        icon: IconPoint,
        href: '/frontend-pages/portfolio',
      },
      {
        id: uniqueId(),
        title: t('navigation.pricing'),
        icon: IconPoint,
        href: '/frontend-pages/pricing',
      },
    ],
  },
  {
    navlabel: true,
    subheader: t('navigation.apps'),
  },
  {
    id: uniqueId(),
    title: t('navigation.Contacts'),
    icon: IconPackage,
    chip: '2',
    chipColor: 'secondary',
    href: '/apps/contacts',
  },

  {
    id: uniqueId(),
    title: t('navigation.Blog'),
    icon: IconChartDonut3,
    href: '/frontend-pages/blog/',
    children: [
      {
        id: uniqueId(),
        title: t('navigation.posts'),
        icon: IconPoint,
        href: '/frontend-pages/blog/',
      },
      {
        id: uniqueId(),
        title: t('navigation.detail'),
        icon: IconPoint,
        href: '/frontend-pages/blog/detail/streaming-video-way-before-it-was-cool-go-dark-tomorrow',
      },
    ],
  },
  {
    id: uniqueId(),
    title: t('navigation.Ecommerce'),
    icon: IconBasket,
    href: '/apps/ecommerce/',
    children: [
      {
        id: uniqueId(),
        title: t('navigation.shop'),
        icon: IconPoint,
        href: '/apps/ecommerce/shop',
      },
      {
        id: uniqueId(),
        title: t('navigation.detail'),
        icon: IconPoint,
        href: '/apps/ecommerce/detail/1',
      },
      {
        id: uniqueId(),
        title: t('navigation.list'),
        icon: IconPoint,
        href: '/apps/ecommerce/eco-product-list',
      },
      {
        id: uniqueId(),
        title: t('navigation.checkout'),
        icon: IconPoint,
        href: '/apps/ecommerce/eco-checkout',
      },
      {
        id: uniqueId(),
        title: t('navigation.addProduct'),
        icon: IconPoint,
        href: '/apps/ecommerce/add-product',
      },
      {
        id: uniqueId(),
        title: t('navigation.editProduct'),
        icon: IconPoint,
        href: '/apps/ecommerce/edit-product',
      },
    ],
  },
  {
    id: uniqueId(),
    title: t('navigation.Chats'),
    icon: IconMessage2,
    href: '/apps/chats',
  },
  {
    id: uniqueId(),
    title: t('navigation.aiChat'),
    icon: IconRobot,
    href: '/apps/ai-chat',
    chip: 'AI',
    chipColor: 'primary',
  },
  {
    id: uniqueId(),
    title: t('navigation.users'),
    icon: IconUserCircle,
    href: '/user-profile',
    children: [
      {
        id: uniqueId(),
        title: t('navigation.profile'),
        icon: IconPoint,
        href: '/user-profile',
      },
      {
        id: uniqueId(),
        title: t('navigation.followers'),
        icon: IconPoint,
        href: '/apps/followers',
      },
      {
        id: uniqueId(),
        title: t('navigation.friends'),
        icon: IconPoint,
        href: '/apps/friends',
      },
      {
        id: uniqueId(),
        title: t('navigation.gallery'),
        icon: IconPoint,
        href: '/apps/gallery',
      },
    ],
  },
  {
    id: uniqueId(),
    title: t('navigation.Notes'),
    icon: IconNotes,
    href: '/apps/notes',
  },
  {
    id: uniqueId(),
    title: t('navigation.Calendar'),
    icon: IconCalendar,
    href: '/apps/calendar',
  },
  {
    id: uniqueId(),
    title: t('navigation.Email'),
    icon: IconMail,
    href: '/apps/email',
  },
  {
    id: uniqueId(),
    title: t('navigation.Tickets'),
    icon: IconTicket,
    href: '/apps/tickets',
  },
  {
    id: uniqueId(),
    title: t('Kanban'),
    icon: IconNotebook,
    href: '/apps/kanban',
  },
  {
    id: uniqueId(),
    title: t('CV Generator'),
    icon: IconFileText,
    href: '/apps/cv-generator',
    chip: 'New',
    chipColor: 'success',
  },
  {
    id: uniqueId(),
    title: t('internships.title'),
    icon: IconAward,
    href: '/apps/internships',
    chip: 'New',
    chipColor: 'primary',
    children: [
      {
        id: uniqueId(),
        title: t('internships.search'),
        icon: IconPoint,
        href: '/apps/internships',
      },
      {
        id: uniqueId(),
        title: t('applications.title'),
        icon: IconPoint,
        href: '/apps/internships/dashboard',
      },
    ],
  },

  {
    id: uniqueId(),
    title: t('companies.title'),
    icon: IconUsers,
    href: '/apps/communication',
    chip: 'New',
    chipColor: 'success',
    children: [
      {
        id: uniqueId(),
        title: t('navigation.chat'),
        icon: IconMessage2,
        href: '/apps/communication?tab=chat',
      },
      {
        id: uniqueId(),
        title: t('dashboard.notifications'),
        icon: IconPoint,
        href: '/apps/communication?tab=notifications',
      },
      {
        id: uniqueId(),
        title: t('applications.documents'),
        icon: IconPoint,
        href: '/apps/communication?tab=documents',
      },
      {
        id: uniqueId(),
        title: t('navigation.meetings'),
        icon: IconCalendar,
        href: '/apps/communication?tab=meetings',
      },
      {
        id: uniqueId(),
        title: t('navigation.Contacts'),
        icon: IconPoint,
        href: '/apps/communication?tab=users',
      },
    ],
  },

  {
    id: uniqueId(),
    title: t('navigation.invoice'),
    icon: IconCurrencyDollar,
    href: '/apps/invoice/',
  },

  {
    navlabel: true,
    subheader: t('navigation.pages'),
  },
  {
    id: uniqueId(),
    title: t('navigation.pricing'),
    icon: IconCurrencyDollar,
    href: '/pages/pricing',
  },
  {
    id: uniqueId(),
    title: t('navigation.accountSetting'),
    icon: IconUserCircle,
    href: '/pages/account-settings',
  },
  {
    id: uniqueId(),
    title: t('navigation.faq'),
    icon: IconHelp,
    href: '/pages/faq',
  },
  {
    id: uniqueId(),
    title: t('navigation.landingpage'),
    icon: IconAppWindow,
    href: '/landingpage',
  },
  {
    id: uniqueId(),
    title: t('navigation.widgets'),
    icon: IconLayout,
    href: '/widgets/cards',
    children: [
      {
        id: uniqueId(),
        title: t('navigation.cards'),
        icon: IconPoint,
        href: '/widgets/cards',
      },
      {
        id: uniqueId(),
        title: t('navigation.banners'),
        icon: IconPoint,
        href: '/widgets/banners',
      },
      {
        id: uniqueId(),
        title: t('navigation.charts'),
        icon: IconPoint,
        href: '/widgets/charts',
      },
    ],
  },
  {
    navlabel: true,
    subheader: t('navigation.forms'),
  },
  {
    id: uniqueId(),
    title: t('navigation.formElements'),
    icon: IconApps,
    href: '/forms/form-elements/autocomplete',
    children: [
      {
        id: uniqueId(),
        title: t('navigation.autocomplete'),
        icon: IconPoint,
        href: '/forms/form-elements/autocomplete',
      },
      {
        id: uniqueId(),
        title: t('navigation.button'),
        icon: IconPoint,
        href: '/forms/form-elements/button',
      },
      {
        id: uniqueId(),
        title: t('navigation.checkbox'),
        icon: IconPoint,
        href: '/forms/form-elements/checkbox',
      },
      {
        id: uniqueId(),
        title: t('navigation.radio'),
        icon: IconPoint,
        href: '/forms/form-elements/radio',
      },
      {
        id: uniqueId(),
        title: t('navigation.dateTime'),
        icon: IconPoint,
        href: '/forms/form-elements/date-time',
      },
      {
        id: uniqueId(),
        title: t('navigation.slider'),
        icon: IconPoint,
        href: '/forms/form-elements/slider',
      },
      {
        id: uniqueId(),
        title: t('navigation.switch'),
        icon: IconPoint,
        href: '/forms/form-elements/switch',
      },
    ],
  },
  {
    id: uniqueId(),
    title: t('navigation.formLayout'),
    icon: IconFileDescription,
    href: '/forms/form-layouts',
  },
  {
    id: uniqueId(),
    title: t('navigation.formHorizontal'),
    icon: IconBoxAlignBottom,
    href: '/forms/form-horizontal',
  },
  {
    id: uniqueId(),
    title: t('navigation.formVertical'),
    icon: IconBoxAlignLeft,
    href: '/forms/form-vertical',
  },
  {
    id: uniqueId(),
    title: t('navigation.formCustom'),
    icon: IconFileDots,
    href: '/forms/form-custom',
  },
  {
    id: uniqueId(),
    title: t('navigation.formWizard'),
    icon: IconFiles,
    href: '/forms/form-wizard',
  },
  {
    id: uniqueId(),
    title: t('navigation.formValidation'),
    icon: IconFiles,
    href: '/forms/form-validation',
  },
  {
    id: uniqueId(),
    title: t('navigation.tiptapEditor'),
    icon: IconEdit,
    href: '/forms/form-tiptap',
  },
  {
    navlabel: true,
    subheader: t('navigation.tables'),
  },
  {
    id: uniqueId(),
    title: t('navigation.basic'),
    icon: IconBorderAll,
    href: '/tables/basic',
  },
  {
    id: uniqueId(),
    title: t('navigation.collapsible'),
    icon: IconBorderHorizontal,
    href: '/tables/collapsible',
  },
  {
    id: uniqueId(),
    title: t('navigation.enhanced'),
    icon: IconBorderInner,
    href: '/tables/enhanced',
  },
  {
    id: uniqueId(),
    title: t('navigation.fixedHeader'),
    icon: IconBorderVertical,
    href: '/tables/fixed-header',
  },
  {
    id: uniqueId(),
    title: t('navigation.pagination'),
    icon: IconBorderTop,
    href: '/tables/pagination',
  },
  {
    id: uniqueId(),
    title: t('navigation.search'),
    icon: IconBorderStyle2,
    href: '/tables/search',
  },
  {
    id: uniqueId(),
    title: t('navigation.reactTable'),
    icon: IconBorderStyle2,
    href: '/react-tables/basic',
    children: [
      {
        id: uniqueId(),
        title: t('navigation.basic'),
        icon: IconPoint,
        href: '/react-tables/basic',
      },
      {
        id: uniqueId(),
        title: t('navigation.dense'),
        icon: IconPoint,
        href: '/react-tables/dense',
      },
      {
        id: uniqueId(),
        title: t('navigation.filter'),
        icon: IconPoint,
        href: '/react-tables/filter',
      },
      {
        id: uniqueId(),
        title: t('navigation.rowSelection'),
        icon: IconPoint,
        href: '/react-tables/row-selection',
      },
      {
        id: uniqueId(),
        title: t('navigation.pagination'),
        icon: IconPoint,
        href: '/react-tables/pagination',
      },
      {
        id: uniqueId(),
        title: t('navigation.sorting'),
        icon: IconPoint,
        href: '/react-tables/sorting',
      },
      {
        id: uniqueId(),
        title: t('navigation.columnVisibility'),
        icon: IconPoint,
        href: '/react-tables/column-visiblity',
      },
      {
        id: uniqueId(),
        title: t('navigation.editable'),
        icon: IconPoint,
        href: '/react-tables/editable',
      },
      {
        id: uniqueId(),
        title: t('navigation.expanding'),
        icon: IconPoint,
        href: '/react-tables/expanding',
      },
      {
        id: uniqueId(),
        title: t('navigation.sticky'),
        icon: IconPoint,
        href: '/react-tables/sticky',
      },
      {
        id: uniqueId(),
        title: t('navigation.empty'),
        icon: IconPoint,
        href: '/react-tables/empty',
      },
      {
        id: uniqueId(),
        title: t('navigation.dragDrop'),
        icon: IconPoint,
        href: '/react-tables/drag-drop',
      },
    ],
  },
  {
    navlabel: true,
    subheader: t('navigation.muiCharts'),
  },

  {
    id: uniqueId(),
    title: 'BarCharts',
    icon: IconChartHistogram,
    href: '/muicharts/barcharts',
  },
  {
    id: uniqueId(),
    title: 'LineCharts',
    icon: IconChartLine,
    href: '/muicharts/linecharts/line',
    children: [
      {
        id: uniqueId(),
        title: 'Lines',
        icon: IconPoint,
        href: '/muicharts/linecharts/line',
      },
      {
        id: uniqueId(),
        title: 'Area',
        icon: IconPoint,
        href: '/muicharts/linecharts/area',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'PieCharts',
    icon: IconChartPie2,
    href: '/muicharts/piecharts',
  },
  {
    id: uniqueId(),
    title: 'ScatterCharts',
    icon: IconChartScatter,
    href: '/muicharts/scattercharts',
  },
  {
    id: uniqueId(),
    title: 'SparklineCharts',
    icon: IconChartPpf,
    href: '/muicharts/sparklinecharts',
  },
  {
    id: uniqueId(),
    title: 'GaugeCharts',
    icon: IconChartArcs3,
    href: '/muicharts/gaugecharts',
  },

  {
    navlabel: true,
    subheader: t('navigation.muiTrees'),
  },
  {
    id: uniqueId(),
    title: 'SimpleTreeView',
    icon: IconListTree,
    href: '/mui-trees/simpletree/simpletree-items',
    children: [
      {
        id: uniqueId(),
        title: 'Items',
        icon: IconPoint,
        href: '/mui-trees/simpletree/simpletree-items',
      },
      {
        id: uniqueId(),
        title: 'Selection',
        icon: IconPoint,
        href: '/mui-trees/simpletree/simpletree-selection',
      },
      {
        id: uniqueId(),
        title: 'Expansion',
        icon: IconPoint,
        href: '/mui-trees/simpletree/simpletree-expansion',
      },
      {
        id: uniqueId(),
        title: 'Customization',
        icon: IconPoint,
        href: '/mui-trees/simpletree/simpletree-customization',
      },
      {
        id: uniqueId(),
        title: 'Focus',
        icon: IconPoint,
        href: '/mui-trees/simpletree/simpletree-focus',
      },
    ],
  },
  {
    navlabel: true,
    subheader: t('navigation.ui'),
  },
  {
    id: uniqueId(),
    title: 'Ui Components',
    icon: IconBox,
    href: '/ui-components/alert',
    children: [
      {
        id: uniqueId(),
        title: 'Alert',
        icon: IconPoint,
        href: '/ui-components/alert',
      },
      {
        id: uniqueId(),
        title: 'Accordion',
        icon: IconPoint,
        href: '/ui-components/accordion',
      },
      {
        id: uniqueId(),
        title: 'Avatar',
        icon: IconPoint,
        href: '/ui-components/avatar',
      },
      {
        id: uniqueId(),
        title: 'Chip',
        icon: IconPoint,
        href: '/ui-components/chip',
      },
      {
        id: uniqueId(),
        title: 'Dialog',
        icon: IconPoint,
        href: '/ui-components/dialog',
      },
      {
        id: uniqueId(),
        title: 'List',
        icon: IconPoint,
        href: '/ui-components/list',
      },
      {
        id: uniqueId(),
        title: 'Popover',
        icon: IconPoint,
        href: '/ui-components/popover',
      },
      {
        id: uniqueId(),
        title: 'Rating',
        icon: IconPoint,
        href: '/ui-components/rating',
      },
      {
        id: uniqueId(),
        title: 'Tabs',
        icon: IconPoint,
        href: '/ui-components/tabs',
      },
      {
        id: uniqueId(),
        title: 'Tooltip',
        icon: IconPoint,
        href: '/ui-components/tooltip',
      },
      {
        id: uniqueId(),
        title: 'Transfer List',
        icon: IconPoint,
        href: '/ui-components/transfer-list',
      },
      {
        id: uniqueId(),
        title: 'Typography',
        icon: IconPoint,
        href: '/ui-components/typography',
      },
    ],
  },

  {
    navlabel: true,
    subheader: t('navigation.charts'),
  },
  {
    id: uniqueId(),
    title: 'Line',
    icon: IconChartLine,
    href: '/charts/line-chart',
  },
  {
    id: uniqueId(),
    title: 'Gredient',
    icon: IconChartArcs,
    href: '/charts/gredient-chart',
  },
  {
    id: uniqueId(),
    title: 'Area',
    icon: IconChartArea,
    href: '/charts/area-chart',
  },
  {
    id: uniqueId(),
    title: 'Candlestick',
    icon: IconChartCandle,
    href: '/charts/candlestick-chart',
  },
  {
    id: uniqueId(),
    title: 'Column',
    icon: IconChartDots,
    href: '/charts/column-chart',
  },
  {
    id: uniqueId(),
    title: 'Doughtnut & Pie',
    icon: IconChartDonut3,
    href: '/charts/doughnut-pie-chart',
  },
  {
    id: uniqueId(),
    title: 'RadialBar & Radar',
    icon: IconChartRadar,
    href: '/charts/radialbar-chart',
  },
  {
    navlabel: true,
    subheader: t('navigation.auth'),
  },

  {
    id: uniqueId(),
    title: 'Login',
    icon: IconLogin,
    href: '/auth/login',
    children: [
      {
        id: uniqueId(),
        title: 'Side Login',
        icon: IconPoint,
        href: '/auth/login',
      },
      {
        id: uniqueId(),
        title: 'Boxed Login',
        icon: IconPoint,
        href: '/auth/login2',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Register',
    icon: IconUserPlus,
    href: '/auth/register',
    children: [
      {
        id: uniqueId(),
        title: 'Side Register',
        icon: IconPoint,
        href: '/auth/register',
      },
      {
        id: uniqueId(),
        title: 'Boxed Register',
        icon: IconPoint,
        href: '/auth/register2',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Forgot Password',
    icon: IconRotate,
    href: '/auth/forgot-password',
    children: [
      {
        id: uniqueId(),
        title: 'Side Forgot Password',
        icon: IconPoint,
        href: '/auth/forgot-password',
      },
      {
        id: uniqueId(),
        title: 'Boxed Forgot Password',
        icon: IconPoint,
        href: '/auth/forgot-password2',
      },
    ],
  },

  {
    id: uniqueId(),
    title: 'Two Steps',
    icon: IconZoomCode,
    href: '/auth/two-steps',
    children: [
      {
        id: uniqueId(),
        title: 'Side Two Steps',
        icon: IconPoint,
        href: '/auth/two-steps',
      },
      {
        id: uniqueId(),
        title: 'Boxed Two Steps',
        icon: IconPoint,
        href: '/auth/two-steps2',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Error',
    icon: IconAlertCircle,
    href: '/400',
  },
  {
    id: uniqueId(),
    title: 'Maintenance',
    icon: IconSettings,
    href: '/auth/maintenance',
  },

  {
    navlabel: true,
    subheader: t('navigation.other'),
  },
  {
    id: uniqueId(),
    title: 'Menu Level',
    icon: IconBoxMultiple,
    href: '/menulevel/',
    children: [
      {
        id: uniqueId(),
        title: 'Level 1',
        icon: IconPoint,
        href: '/l1',
      },
      {
        id: uniqueId(),
        title: 'Level 1.1',
        icon: IconPoint,
        href: '/l1.1',
        children: [
          {
            id: uniqueId(),
            title: 'Level 2',
            icon: IconPoint,
            href: '/l2',
          },
          {
            id: uniqueId(),
            title: 'Level 2.1',
            icon: IconPoint,
            href: '/l2.1',
            children: [
              {
                id: uniqueId(),
                title: 'Level 3',
                icon: IconPoint,
                href: '/l3',
              },
              {
                id: uniqueId(),
                title: 'Level 3.1',
                icon: IconPoint,
                href: '/l3.1',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Disabled',
    icon: IconBan,
    href: '/',
    disabled: true,
  },
  {
    id: uniqueId(),
    title: 'SubCaption',
    subtitle: 'This is the sutitle',
    icon: IconStar,
    href: '/',
  },

  {
    id: uniqueId(),
    title: 'Chip',
    icon: IconAward,
    href: '/',
    chip: '9',
    chipColor: 'primary',
  },
  {
    id: uniqueId(),
    title: 'Outlined',
    icon: IconMoodSmile,
    href: '/',
    chip: 'outline',
    variant: 'outlined',
    chipColor: 'primary',
  },
  {
    id: uniqueId(),
    title: 'External Link',
    external: true,
    icon: IconStar,
    href: 'https://google.com',
  },
  ];
};

export default useMenuItems;
